export const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
export const CROP_TYPES = [
  "Arecanut",
  "Arhar/Tur",
  "Castor seed",
  "Coconut",
  "Cotton(lint)",
  "Dry chillies",
  "Gram",
  "Jute",
  "Linseed",
  "Maize",
  "Mesta",
  "Niger seed",
  "Onion",
  "Other  Rabi pulses",
  "Potato",
  "Rapeseed &Mustard",
  "Rice",
  "Sesamum",
  "Small millets",
  "Sugarcane",
  "Sweet potato",
  "Tapioca",
  "Tobacco",
  "Turmeric",
  "Wheat",
  "Bajra",
  "Black pepper",
  "Cardamom",
  "Coriander",
  "Garlic",
  "Ginger",
  "Groundnut",
  "Horse-gram",
  "Jowar",
  "Ragi",
  "Cashewnut",
  "Banana",
  "Soyabean",
  "Barley",
  "Khesari",
  "Masoor",
  "Moong(Green Gram)",
  "Other Kharif pulses",
  "Safflower",
  "Sannhamp",
  "Sunflower",
  "Urad",
  "Peas & beans (Pulses)",
  "other oilseeds",
  "Other Cereals",
  "Cowpea(Lobia)",
  "Oilseeds total",
  "Guar seed",
  "Other Summer Pulses",
  "Moth",
];

export const SOIL_TYPE = [
  "Alluvial Soil",
  "Black Soil",
  "Red Soil",
  "Laterite Soil",
  "Desert Soil",
  "Saline Soil",
  "Peaty Soil",
  "Forest Soil",
  "Mountain Soil",
  "Clay Soil",
  "Loamy Soil",
];

export const DISTRICTS = {
  "Andhra Pradesh": ["Anantapur", "Chittoor", "Guntur", "Krishna", "Kurnool"],
  "Arunachal Pradesh": [
    "Anjaw",
    "Changlang",
    "East Siang",
    "Papum Pare",
    "Tawang",
  ],
  Assam: ["Baksa", "Barpeta", "Dibrugarh", "Jorhat", "Kamrup"],
  Bihar: ["Araria", "Bhagalpur", "Gaya", "Muzaffarpur", "Patna"],
  Chhattisgarh: ["Bilaspur", "Durg", "Korba", "Raigarh", "Raipur"],
  Goa: ["North Goa", "South Goa"],
  Gujarat: ["Ahmedabad", "Rajkot", "Surat", "Vadodara", "Kutch"],
  Haryana: ["Ambala", "Faridabad", "Gurugram", "Karnal", "Rohtak"],
  "Himachal Pradesh": ["Bilaspur", "Kangra", "Kullu", "Shimla", "Solan"],
  Jharkhand: ["Bokaro", "Dhanbad", "Jamshedpur", "Ranchi", "Hazaribagh"],
  Karnataka: ["Bengaluru", "Mysuru", "Dharwad", "Shivamogga", "Udupi"],
  Kerala: [
    "Alappuzha",
    "Ernakulam",
    "Kozhikode",
    "Thiruvananthapuram",
    "Thrissur",
  ],
  "Madhya Pradesh": ["Bhopal", "Gwalior", "Indore", "Jabalpur", "Ujjain"],
  Maharashtra: ["Mumbai", "Pune", "Nagpur", "Nashik", "Aurangabad"],
  Manipur: ["Bishnupur", "Chandel", "Imphal East", "Imphal West", "Thoubal"],
  Meghalaya: [
    "East Khasi Hills",
    "West Khasi Hills",
    "Ri-Bhoi",
    "South Garo Hills",
    "West Garo Hills",
  ],
  Mizoram: ["Aizawl", "Kolasib", "Lawngtlai", "Lunglei", "Serchhip"],
  Nagaland: ["Dimapur", "Kohima", "Mokokchung", "Tuensang", "Wokha"],
  Odisha: ["Balasore", "Cuttack", "Ganjam", "Kendujhar", "Khordha"],
  Punjab: ["Amritsar", "Jalandhar", "Ludhiana", "Patiala", "Sangrur"],
  Rajasthan: ["Jaipur", "Jodhpur", "Kota", "Udaipur", "Ajmer"],
  Sikkim: ["East Sikkim", "North Sikkim", "South Sikkim", "West Sikkim"],
  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Salem",
    "Tiruchirappalli",
  ],
  Telangana: ["Adilabad", "Hyderabad", "Karimnagar", "Khammam", "Warangal"],
  Tripura: [
    "Dhalai",
    "Gomati",
    "West Tripura",
    "North Tripura",
    "South Tripura",
  ],
  "Uttar Pradesh": ["Agra", "Allahabad", "Lucknow", "Varanasi", "Kanpur"],
  Uttarakhand: ["Almora", "Dehradun", "Haridwar", "Nainital", "Pauri Garhwal"],
  "West Bengal": ["Kolkata", "Howrah", "Darjeeling", "Murshidabad", "Nadia"],
};
