export const STATES = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
];
export const CROP_TYPES = [
  "Arecanut",
  "Arhar/Tur",
  "Castor seed",
  "Coconut",
  "Cotton(lint)",
  "Dry chillies",
  "Gram",
  "Jute",
  "Linseed",
  "Maize",
  "Mesta",
  "Niger seed",
  "Onion",
  "Other  Rabi pulses",
  "Potato",
  "Rapeseed &Mustard",
  "Rice",
  "Sesamum",
  "Small millets",
  "Sugarcane",
  "Sweet potato",
  "Tapioca",
  "Tobacco",
  "Turmeric",
  "Wheat",
  "Bajra",
  "Black pepper",
  "Cardamom",
  "Coriander",
  "Garlic",
  "Ginger",
  "Groundnut",
  "Horse-gram",
  "Jowar",
  "Ragi",
  "Cashewnut",
  "Banana",
  "Soyabean",
  "Barley",
  "Khesari",
  "Masoor",
  "Moong(Green Gram)",
  "Other Kharif pulses",
  "Safflower",
  "Sannhamp",
  "Sunflower",
  "Urad",
  "Peas & beans (Pulses)",
  "other oilseeds",
  "Other Cereals",
  "Cowpea(Lobia)",
  "Oilseeds total",
  "Guar seed",
  "Other Summer Pulses",
  "Moth",
];

export const SOIL_TYPE = [
  "Alluvial Soil",
  "Black Soil",
  "Red Soil",
  "Laterite Soil",
  "Desert Soil",
  "Saline Soil",
  "Peaty Soil",
  "Forest Soil",
  "Mountain Soil",
  "Clay Soil",
  "Loamy Soil",
];
